---

- hosts: all
  become: true
  tasks:
  - name: install ntp ntpdate ntpstat package
    apt: 
      name: 
        - ntp
        - ntpdate
        - ntpstat
      update_cache: yes
    when: ansible_distribution == ["Debian", "Ubuntu"]

