---
- hosts: localhost
  connection: local
  become: true

  pre_tasks:
  - name: Update all repositories APT based systems
    tags: always
    apt:
      update_cache: yes
    when: ansible_distribution in ["Ubuntu", "Debian"]
    changed_when: False

  - name: Update all repositories PACMAN based systems
    tags: always
    pacman:
      update_cache: yes
    when: ansible_distribution in ["Archlinux"]
    changed_when: False

  tasks:
    - include: tasks/apps.yml
    - include: tasks/users.yml
    - include: tasks/cron.yml
