---
- hosts: localhost
  connection: local
  become: true

  pre_tasks:
  - name: Update apt repo and cache on all ubuntu and debian distros
    tags: always
    apt:
      upgrade: dist
      update_cache: yes

  - name: Update all packages
    tags: always
    apt:
      upgrade: dist

  tasks:
    - include: tasks/users.yml
    - include: tasks/cron.yml
