---

- hosts: all
  become: true
  tasks:
  - name: install updates(all)
    package:
      upgrade: dist
      update_cache: yes

  - name: install ntp ntpdate ntpstat package
    package: 
      name: 
        - "ntp"
        - "ntpdate"
        - "ntpstat"

