---

- hosts: all
  become: true
  pre_tasks:

  - name: install updates(all)
    tags: always
    dnf:
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "CentOS"

  - name: install updates (Ubuntu, Debian)
    tags: always
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == ["Ubuntu", "Debian"]

  - name: copy file test
    tags: always
    copy:
      src: default_site.yml
      dest: /root/index.html
      owner: root
      group: root
      mode: 0644

