---

- hosts: boinc,web_servers,test_servers
  become: true
  pre_tasks:

  - name: install updates (Ubuntu, Debian)
    tags: always
    apt:
      update_cache: yes
      upgrade: dist

- hosts: laptop
  connection: local
  become: true
  pre_tasks:

  - name: Localhost update
    tags: always
    apt:
      update_cache: yes
      upgrade: dist
#Is this still needed?
