  - name: Install default apps via APT
    become: true
    apt:
      state: latest
      name:     
       - ansible
       - git
       - screen
       - wget
       - htop
       - unzip
       - python3
       - python3-pip
       - cmatrix
       - nano
       - mc
       - tmux
      update_cache: true
    when: ansible_distribution in ["Ubuntu", "Debian"]

  - name: Install default apps via PACMAN
    become: true
    pacman:
      state: latest     
      name:     
       - ansible
       - git
       - screen
       - wget
       - htop
       - unzip
       - python
       - python-pip
       - cronie
       - vi
       - nano
       - iftop
       - htop
       - cmatrix
       - mc
       - tmux
       - openssh
      update_cache: true
    when: ansible_distribution in ["Archlinux"]
  
  - name: Enable SSHD on ArchLinux
    command: systemctl enable sshd
    tags: 
      - sshd
    when: ansible_distribution in ["Archlinux"]
      
