  - name: Install default apps
    become: true
    apt:
      state: present     
      name:     
       - ansible
       - git
       - screen
       - wget
       - htop
       - unzip
       - python3
       - python3-pip
       - cronie
      update_cache: true
