  - name: Install default apps via APT
    become: true
    apt:
      state: present     
      name:     
       - ansible
       - git
       - screen
       - wget
       - htop
       - unzip
       - python3
       - python3-pip
       - cronie
      update_cache: true
    when: ansible_distribution in ["Ubuntu", "Debian"]

  - name: Install default apps via PACMAN
    become: true
    pacman:
      state: present     
      name:     
       - ansible
       - git
       - screen
       - wget
       - htop
       - unzip
       - python3
       - python3-pip
       - cronie
      update_cache: true
    when: ansible_distribution in ["Archlinux"]
