- name: remove old cron job (ansible-pull)
  cron:
    user: ansible
    name: "ansible provision"
    minute: "*/10"
    job: "/usr/bin/ansible-pull -o -U https://github.com/kizeren/ansible_control.git > /dev/null"
    state: absent
- name: add new website cron job (ansible-pull)
  cron:
    user: ansible
    name: "ansible provision local"
    job: "/usr/bin/ansible-pull -o -U http://gitlab.local.lan/root/ansible_control.git > /dev/null"
    state: present
