  - name: create ansible user
    tags: always
    user:
      name: ansible
      system: yes

  - name: add sudoers file for ansible
    tags: always
    copy:
      src: sudoer_ansible
      dest: /etc/sudoers.d/ansible
      owner: root
      group: root
      mode: 0440

  - name: Add key for ansible
    tags: always
    authorized_key:
      user: ansible
      key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIGcOvIwsLrph2bDBuiQ139gLZw/qOvnmEHcPEpEjWRwz Ansible Only"

